### ISSUE TITLE
A python runtime error

### ISSUE THREAD

**Issue by ghost** [wangkuiyi/mapreduce-lite#3]
I built this project successfully, but some errors occurred when I try to run it in the single machine model.

I modify the IP variable to 127.0.0.1 and chmod +x wordcount_run_locally.sh

when I run ./wordcount_run_locally.sh, the error occurred in util.py, error trace shows :

``` shell
mrlite.py: Job started at Mon Sep  1 20:28:21 2014
mrlite.py: Copy binary executable and python scripts to machines
Traceback (most recent call last):
  File "../scheduler/mrlite.py", line 279, in <module>
    main(sys.argv[1:])
  File "../scheduler/mrlite.py", line 257, in main
    scheduler = MRLiteJobScheduler(options)
  File "../scheduler/mrlite.py", line 85, in __init__
    self.dispatch_file(file_list, options.mapreduce_tmp_dir)
  File "/home/alex/mapreduce-lite/scheduler/util.py", line 126, in dispatch_file
    self.wait_cmd(process, cmd_scp)
  File "/home/alex/mapreduce-lite/scheduler/util.py", line 92, in wait_cmd
    raise RuntimeError(mesg)
RuntimeError: Fail with retcode(255): mkdir -p /tmp/mrlite-alex
```

It seems that there are somethings wrong in function : wait_cmd(process, cmd_scp)
the retcode is 255, but seems Useless.

I tested it on Ubuntu 13.04 and 14.04, the error is the same.

**Comment by ghost** [comment]
By the way, the source code is the google code version. The github version I can't built sucessfully, I modified the CMakeList and Make sure program can find the libraries but there is still a error.

**Comment by yhcharles** [comment]
We may need to contact Rick to check this issue

**Comment by HelloSunyi** [comment]
Do you solve this problem? I meet this problem too, and I don't know how to solve it.

**Comment by agamal94** [comment]
I compiled the latest version and i got the same error. anybody figured out the solution yet?

Update:
I was able to run the local demo by fixing some issues with ssh connection
1- make sure that you have  openssh-server and client
2- edit the value PermitRootLogin to be yes (if you are using root account) located in /etc/ssh/sshd_config
3- the demo uses port number 3600 instead of the default port (22) change one of them.
